require 'rake'
require 'opal'
require 'opal/browser'

task :default => ["./opal-#{Opal::VERSION}.js", "./opal-parser.js", "./opal-browser.js", "./opal-source-maps.js" ]

file "./opal-#{Opal::VERSION}.js" => ["./opal-master/opal/opal.rb" ] do |t|
  sh "bundle exec opal -I ./opal-master/opal --compile #{t.prerequisites[0]} > #{t.name}"
end

file "./opal-master/opal/opal.rb" do |t|
  sh "bundle exec gem unpack opal"
end

file "./opal-parser.js" => ["./opal-master/stdlib/opal-parser.rb" ] do |t|
  sh "bundle exec opal -O -I ./opal-master/opal --compile #{t.prerequisites[0]} > #{t.name}"
end

file "./opal-master/stdlib/opal-parser.rb" do |t|
  sh "bundle exec gem unpack opal"
end

file "./opal-source-maps.js" => ["./opal-master/stdlib/opal-source-maps.rb" ] do |t|
  sh "bundle exec opal -O -I ./opal-master/opal --compile #{t.prerequisites[0]} > #{t.name}"
end

file "./opal-master/stdlib/opal-source-maps.rb" do |t|
  sh "bundle exec gem unpack opal"
end

file "./opal-browser.js" => ["./opal-browser-*/opal/opal-browser.rb" ] do |t|
  sh "bundle exec opal -O -I ./opal-browser-*/opal -r 'browser/delay' --gem paggio --compile #{t.prerequisites[0]} > #{t.name}"
end

file "./opal-browser-*/opal/opal-browser.rb" do |t|
  sh "bundle exec gem unpack opal-browser"
end

