/**
 * @brief 外部割り込みのフックの許可/禁止を設定するファイル
 *
 * - ENABLE_EXTINT_CAPTURE(name) : 名前 name の外部割り込みのフックを許可する
 * - DISABLE_EXTINT_CAPTURE(name) : 名前 name の外部割り込みのフックを禁止する
 */

#ifndef ENABLE_EXTINT_CAPTURE
/**
 * @def             ENABLE_EXTINT_CAPTURE
 * @brief           外部割り込み name はフック可能とする
 * @param   name    AVRの割り込み名
 */
#define ENABLE_EXTINT_CAPTURE(name)
#endif

#ifndef DISABLE_EXTINT_CAPTURE
/**
 * @def             DISABLE_EXTINT_CAPTURE
 * @brief           外部割り込み name はフック不能とする
 * @param   name    AVRの割り込み名
 */
#define DISABLE_EXTINT_CAPTURE(name) case EXTINT_##name: return false;
#endif

/* リセット割り込みはフック禁止 */
DISABLE_EXTINT_CAPTURE(RESET)
/* INT0割り込みはソフトウェア割り込みで使用するためフック禁止 */
DISABLE_EXTINT_CAPTURE(INT0)
ENABLE_EXTINT_CAPTURE(INT1)
ENABLE_EXTINT_CAPTURE(PCINT0)
ENABLE_EXTINT_CAPTURE(PCINT1)
ENABLE_EXTINT_CAPTURE(PCINT2)
ENABLE_EXTINT_CAPTURE(WDT)
ENABLE_EXTINT_CAPTURE(TIMER2_COMPA)
ENABLE_EXTINT_CAPTURE(TIMER2_COMPB)
ENABLE_EXTINT_CAPTURE(TIMER2_OVF)
#if     (F_CPU == 20000000UL) || (F_CPU == 16000000UL)
/* CPUクロックが20Mhz/16Mhzの場合、TIMER0をカーネルタイマとして使用するためフック禁止 */
ENABLE_EXTINT_CAPTURE(TIMER1_CAPT)
ENABLE_EXTINT_CAPTURE(TIMER1_COMPA)
ENABLE_EXTINT_CAPTURE(TIMER1_COMPB)
ENABLE_EXTINT_CAPTURE(TIMER1_OVF)
DISABLE_EXTINT_CAPTURE(TIMER0_COMPA)
DISABLE_EXTINT_CAPTURE(TIMER0_COMPB)
DISABLE_EXTINT_CAPTURE(TIMER0_OVF)
#elif   (F_CPU == 12000000UL) || (F_CPU ==  8000000UL)
/* CPUクロックが12Mhz/8Mhzの場合、TIMER1をカーネルタイマとして使用するためフック禁止 */
DISABLE_EXTINT_CAPTURE(TIMER1_CAPT)
DISABLE_EXTINT_CAPTURE(TIMER1_COMPA)
DISABLE_EXTINT_CAPTURE(TIMER1_COMPB)
DISABLE_EXTINT_CAPTURE(TIMER1_OVF)
ENABLE_EXTINT_CAPTURE(TIMER0_COMPA)
ENABLE_EXTINT_CAPTURE(TIMER0_COMPB)
ENABLE_EXTINT_CAPTURE(TIMER0_OVF)
#endif
ENABLE_EXTINT_CAPTURE(SPI_STC)
ENABLE_EXTINT_CAPTURE(USART_RX)
ENABLE_EXTINT_CAPTURE(USART_UDRE)
ENABLE_EXTINT_CAPTURE(USART_TX)
ENABLE_EXTINT_CAPTURE(ADC)
ENABLE_EXTINT_CAPTURE(EE_READY)
ENABLE_EXTINT_CAPTURE(ANALOG_COMP)
ENABLE_EXTINT_CAPTURE(TWI)
ENABLE_EXTINT_CAPTURE(SPM_READY)

