CC=gcc -Wall -Wextra -pedantic -std=c89 -ansi
FILES=$(shell ls *.c)
OUTDIR=gcc-result

TARGETS=$(patsubst %.c,$(OUTDIR)/%.o,$(FILES))

.phony: all

all: $(TARGETS)

$(TARGETS): $(OUTDIR)/%.o: %.c
	-$(CC) -o $@ -c $< > $(OUTDIR)/$*.log 2>&1

$(OUTDIR):
	mkdir -p $(OUTDIR)



